name: example
description: Example app demonstrating animated_bubble_background usage
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Publishing এর জন্য version-based dependency
  animated_bubble_background: ^1.0.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Publishing command এর জন্য
publish_to: none  # Example app publish করবেন না