name: animated_bubble_background
description: A beautiful animated bubble background widget for Flutter apps with customizable colors, sizes, and animation speeds.
version: 0.0.1
license: MIT

homepage: https://github.com/moshaddaque/animated_bubble_background

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Optional: If you want to add screenshots
flutter:
  # assets:
  #   - images/

topics:
  - animation
  - background
  - bubble
  - ui
  - widget